rootProject.name = "otus-pro-homeworks"
include("hw01-gradle")
include("hw02-unittest")
include("hw03-generic")
include("hw04-gc")
include("hw05-annotations")
include("cw12-creational-patterns")
include("hw06-solid")
include("cw13-behavioral-patterns")
include("cw14-structural-patterns")