rootProject.name = "otus-pro-homeworks"
include("cw01-gradle")
include("cw02-unittest")
include("cw03-generic")
include("cw05-docker")
include("cw04-gc")
include("cw06-annotation")
include("cw07-functional-programming")
include("cw08-clean-code")
include("cw09-troubleshooting")
include("cw10-solid")
include("cw11-stream")
