server:
  port: 9191
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: otus1.p12
    key-store-password: 123456
    key-alias: otus
#  truststore:
#    store: truststore.p12
#    password: 123456
logging:
  level:
    root: debug
spring:
  sql:
    init:
#      mode: always
      platform: hsqldb
  jpa:
    defer-datasource-initialization: true