#Реализовать хранение креденшелов в переменных окружения
server:
  port: 8190
  servlet:
    context-path: /worker
spring:
  datasource:
        platform: oracle
        driverClassName: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@//localhost:1521/xe
        username: ${TARGET_DB_USERNAME}
        password: ${TARGET_DB_PASSWORD}
  jpa:
    show-sql: true
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE