// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string chatIdentifier = 1;</code>
     * @return The chatIdentifier.
     */
    java.lang.String getChatIdentifier();
    /**
     * <code>string chatIdentifier = 1;</code>
     * @return The bytes for chatIdentifier.
     */
    com.google.protobuf.ByteString
        getChatIdentifierBytes();

    /**
     * <code>string membersLast = 2;</code>
     * @return The membersLast.
     */
    java.lang.String getMembersLast();
    /**
     * <code>string membersLast = 2;</code>
     * @return The bytes for membersLast.
     */
    com.google.protobuf.ByteString
        getMembersLastBytes();

    /**
     * <code>string belongNumber = 3;</code>
     * @return The belongNumber.
     */
    java.lang.String getBelongNumber();
    /**
     * <code>string belongNumber = 3;</code>
     * @return The bytes for belongNumber.
     */
    com.google.protobuf.ByteString
        getBelongNumberBytes();

    /**
     * <code>.google.protobuf.Timestamp sendDate = 4;</code>
     * @return Whether the sendDate field is set.
     */
    boolean hasSendDate();
    /**
     * <code>.google.protobuf.Timestamp sendDate = 4;</code>
     * @return The sendDate.
     */
    com.google.protobuf.Timestamp getSendDate();
    /**
     * <code>.google.protobuf.Timestamp sendDate = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getSendDateOrBuilder();

    /**
     * <code>string text = 5;</code>
     * @return The text.
     */
    java.lang.String getText();
    /**
     * <code>string text = 5;</code>
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      chatIdentifier_ = "";
      membersLast_ = "";
      belongNumber_ = "";
      text_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageOuterClass.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageOuterClass.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageOuterClass.Message.class, MessageOuterClass.Message.Builder.class);
    }

    private int bitField0_;
    public static final int CHATIDENTIFIER_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object chatIdentifier_ = "";
    /**
     * <code>string chatIdentifier = 1;</code>
     * @return The chatIdentifier.
     */
    @java.lang.Override
    public java.lang.String getChatIdentifier() {
      java.lang.Object ref = chatIdentifier_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chatIdentifier_ = s;
        return s;
      }
    }
    /**
     * <code>string chatIdentifier = 1;</code>
     * @return The bytes for chatIdentifier.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChatIdentifierBytes() {
      java.lang.Object ref = chatIdentifier_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatIdentifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEMBERSLAST_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object membersLast_ = "";
    /**
     * <code>string membersLast = 2;</code>
     * @return The membersLast.
     */
    @java.lang.Override
    public java.lang.String getMembersLast() {
      java.lang.Object ref = membersLast_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        membersLast_ = s;
        return s;
      }
    }
    /**
     * <code>string membersLast = 2;</code>
     * @return The bytes for membersLast.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMembersLastBytes() {
      java.lang.Object ref = membersLast_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        membersLast_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BELONGNUMBER_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object belongNumber_ = "";
    /**
     * <code>string belongNumber = 3;</code>
     * @return The belongNumber.
     */
    @java.lang.Override
    public java.lang.String getBelongNumber() {
      java.lang.Object ref = belongNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        belongNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string belongNumber = 3;</code>
     * @return The bytes for belongNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBelongNumberBytes() {
      java.lang.Object ref = belongNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        belongNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDDATE_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp sendDate_;
    /**
     * <code>.google.protobuf.Timestamp sendDate = 4;</code>
     * @return Whether the sendDate field is set.
     */
    @java.lang.Override
    public boolean hasSendDate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp sendDate = 4;</code>
     * @return The sendDate.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getSendDate() {
      return sendDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendDate_;
    }
    /**
     * <code>.google.protobuf.Timestamp sendDate = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getSendDateOrBuilder() {
      return sendDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendDate_;
    }

    public static final int TEXT_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object text_ = "";
    /**
     * <code>string text = 5;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 5;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chatIdentifier_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, chatIdentifier_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(membersLast_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, membersLast_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(belongNumber_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, belongNumber_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(4, getSendDate());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, text_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chatIdentifier_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, chatIdentifier_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(membersLast_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, membersLast_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(belongNumber_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, belongNumber_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getSendDate());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, text_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessageOuterClass.Message)) {
        return super.equals(obj);
      }
      MessageOuterClass.Message other = (MessageOuterClass.Message) obj;

      if (!getChatIdentifier()
          .equals(other.getChatIdentifier())) return false;
      if (!getMembersLast()
          .equals(other.getMembersLast())) return false;
      if (!getBelongNumber()
          .equals(other.getBelongNumber())) return false;
      if (hasSendDate() != other.hasSendDate()) return false;
      if (hasSendDate()) {
        if (!getSendDate()
            .equals(other.getSendDate())) return false;
      }
      if (!getText()
          .equals(other.getText())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHATIDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getChatIdentifier().hashCode();
      hash = (37 * hash) + MEMBERSLAST_FIELD_NUMBER;
      hash = (53 * hash) + getMembersLast().hashCode();
      hash = (37 * hash) + BELONGNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getBelongNumber().hashCode();
      if (hasSendDate()) {
        hash = (37 * hash) + SENDDATE_FIELD_NUMBER;
        hash = (53 * hash) + getSendDate().hashCode();
      }
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessageOuterClass.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageOuterClass.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageOuterClass.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageOuterClass.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageOuterClass.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageOuterClass.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageOuterClass.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageOuterClass.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static MessageOuterClass.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static MessageOuterClass.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageOuterClass.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageOuterClass.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessageOuterClass.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        MessageOuterClass.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageOuterClass.internal_static_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageOuterClass.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageOuterClass.Message.class, MessageOuterClass.Message.Builder.class);
      }

      // Construct using MessageOuterClass.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSendDateFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        chatIdentifier_ = "";
        membersLast_ = "";
        belongNumber_ = "";
        sendDate_ = null;
        if (sendDateBuilder_ != null) {
          sendDateBuilder_.dispose();
          sendDateBuilder_ = null;
        }
        text_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageOuterClass.internal_static_Message_descriptor;
      }

      @java.lang.Override
      public MessageOuterClass.Message getDefaultInstanceForType() {
        return MessageOuterClass.Message.getDefaultInstance();
      }

      @java.lang.Override
      public MessageOuterClass.Message build() {
        MessageOuterClass.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MessageOuterClass.Message buildPartial() {
        MessageOuterClass.Message result = new MessageOuterClass.Message(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(MessageOuterClass.Message result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.chatIdentifier_ = chatIdentifier_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.membersLast_ = membersLast_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.belongNumber_ = belongNumber_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.sendDate_ = sendDateBuilder_ == null
              ? sendDate_
              : sendDateBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.text_ = text_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageOuterClass.Message) {
          return mergeFrom((MessageOuterClass.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageOuterClass.Message other) {
        if (other == MessageOuterClass.Message.getDefaultInstance()) return this;
        if (!other.getChatIdentifier().isEmpty()) {
          chatIdentifier_ = other.chatIdentifier_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getMembersLast().isEmpty()) {
          membersLast_ = other.membersLast_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getBelongNumber().isEmpty()) {
          belongNumber_ = other.belongNumber_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasSendDate()) {
          mergeSendDate(other.getSendDate());
        }
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                chatIdentifier_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                membersLast_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                belongNumber_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getSendDateFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                text_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object chatIdentifier_ = "";
      /**
       * <code>string chatIdentifier = 1;</code>
       * @return The chatIdentifier.
       */
      public java.lang.String getChatIdentifier() {
        java.lang.Object ref = chatIdentifier_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          chatIdentifier_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string chatIdentifier = 1;</code>
       * @return The bytes for chatIdentifier.
       */
      public com.google.protobuf.ByteString
          getChatIdentifierBytes() {
        java.lang.Object ref = chatIdentifier_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chatIdentifier_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string chatIdentifier = 1;</code>
       * @param value The chatIdentifier to set.
       * @return This builder for chaining.
       */
      public Builder setChatIdentifier(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        chatIdentifier_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string chatIdentifier = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChatIdentifier() {
        chatIdentifier_ = getDefaultInstance().getChatIdentifier();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string chatIdentifier = 1;</code>
       * @param value The bytes for chatIdentifier to set.
       * @return This builder for chaining.
       */
      public Builder setChatIdentifierBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        chatIdentifier_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object membersLast_ = "";
      /**
       * <code>string membersLast = 2;</code>
       * @return The membersLast.
       */
      public java.lang.String getMembersLast() {
        java.lang.Object ref = membersLast_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          membersLast_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string membersLast = 2;</code>
       * @return The bytes for membersLast.
       */
      public com.google.protobuf.ByteString
          getMembersLastBytes() {
        java.lang.Object ref = membersLast_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          membersLast_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string membersLast = 2;</code>
       * @param value The membersLast to set.
       * @return This builder for chaining.
       */
      public Builder setMembersLast(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        membersLast_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string membersLast = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMembersLast() {
        membersLast_ = getDefaultInstance().getMembersLast();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string membersLast = 2;</code>
       * @param value The bytes for membersLast to set.
       * @return This builder for chaining.
       */
      public Builder setMembersLastBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        membersLast_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object belongNumber_ = "";
      /**
       * <code>string belongNumber = 3;</code>
       * @return The belongNumber.
       */
      public java.lang.String getBelongNumber() {
        java.lang.Object ref = belongNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          belongNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string belongNumber = 3;</code>
       * @return The bytes for belongNumber.
       */
      public com.google.protobuf.ByteString
          getBelongNumberBytes() {
        java.lang.Object ref = belongNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          belongNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string belongNumber = 3;</code>
       * @param value The belongNumber to set.
       * @return This builder for chaining.
       */
      public Builder setBelongNumber(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        belongNumber_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string belongNumber = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBelongNumber() {
        belongNumber_ = getDefaultInstance().getBelongNumber();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string belongNumber = 3;</code>
       * @param value The bytes for belongNumber to set.
       * @return This builder for chaining.
       */
      public Builder setBelongNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        belongNumber_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp sendDate_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> sendDateBuilder_;
      /**
       * <code>.google.protobuf.Timestamp sendDate = 4;</code>
       * @return Whether the sendDate field is set.
       */
      public boolean hasSendDate() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp sendDate = 4;</code>
       * @return The sendDate.
       */
      public com.google.protobuf.Timestamp getSendDate() {
        if (sendDateBuilder_ == null) {
          return sendDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendDate_;
        } else {
          return sendDateBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp sendDate = 4;</code>
       */
      public Builder setSendDate(com.google.protobuf.Timestamp value) {
        if (sendDateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sendDate_ = value;
        } else {
          sendDateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendDate = 4;</code>
       */
      public Builder setSendDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (sendDateBuilder_ == null) {
          sendDate_ = builderForValue.build();
        } else {
          sendDateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendDate = 4;</code>
       */
      public Builder mergeSendDate(com.google.protobuf.Timestamp value) {
        if (sendDateBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            sendDate_ != null &&
            sendDate_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getSendDateBuilder().mergeFrom(value);
          } else {
            sendDate_ = value;
          }
        } else {
          sendDateBuilder_.mergeFrom(value);
        }
        if (sendDate_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendDate = 4;</code>
       */
      public Builder clearSendDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sendDate_ = null;
        if (sendDateBuilder_ != null) {
          sendDateBuilder_.dispose();
          sendDateBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendDate = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getSendDateBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getSendDateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp sendDate = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getSendDateOrBuilder() {
        if (sendDateBuilder_ != null) {
          return sendDateBuilder_.getMessageOrBuilder();
        } else {
          return sendDate_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : sendDate_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp sendDate = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getSendDateFieldBuilder() {
        if (sendDateBuilder_ == null) {
          sendDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getSendDate(),
                  getParentForChildren(),
                  isClean());
          sendDate_ = null;
        }
        return sendDateBuilder_;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 5;</code>
       * @return The text.
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 5;</code>
       * @return The bytes for text.
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 5;</code>
       * @param value The text to set.
       * @return This builder for chaining.
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        text_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearText() {
        text_ = getDefaultInstance().getText();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string text = 5;</code>
       * @param value The bytes for text to set.
       * @return This builder for chaining.
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        text_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final MessageOuterClass.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessageOuterClass.Message();
    }

    public static MessageOuterClass.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MessageOuterClass.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MessageList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Message messages = 1;</code>
     */
    java.util.List<MessageOuterClass.Message> 
        getMessagesList();
    /**
     * <code>repeated .Message messages = 1;</code>
     */
    MessageOuterClass.Message getMessages(int index);
    /**
     * <code>repeated .Message messages = 1;</code>
     */
    int getMessagesCount();
    /**
     * <code>repeated .Message messages = 1;</code>
     */
    java.util.List<? extends MessageOuterClass.MessageOrBuilder> 
        getMessagesOrBuilderList();
    /**
     * <code>repeated .Message messages = 1;</code>
     */
    MessageOuterClass.MessageOrBuilder getMessagesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code MessageList}
   */
  public static final class MessageList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MessageList)
      MessageListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageList.newBuilder() to construct.
    private MessageList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageList() {
      messages_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageOuterClass.internal_static_MessageList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageOuterClass.internal_static_MessageList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageOuterClass.MessageList.class, MessageOuterClass.MessageList.Builder.class);
    }

    public static final int MESSAGES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<MessageOuterClass.Message> messages_;
    /**
     * <code>repeated .Message messages = 1;</code>
     */
    @java.lang.Override
    public java.util.List<MessageOuterClass.Message> getMessagesList() {
      return messages_;
    }
    /**
     * <code>repeated .Message messages = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends MessageOuterClass.MessageOrBuilder> 
        getMessagesOrBuilderList() {
      return messages_;
    }
    /**
     * <code>repeated .Message messages = 1;</code>
     */
    @java.lang.Override
    public int getMessagesCount() {
      return messages_.size();
    }
    /**
     * <code>repeated .Message messages = 1;</code>
     */
    @java.lang.Override
    public MessageOuterClass.Message getMessages(int index) {
      return messages_.get(index);
    }
    /**
     * <code>repeated .Message messages = 1;</code>
     */
    @java.lang.Override
    public MessageOuterClass.MessageOrBuilder getMessagesOrBuilder(
        int index) {
      return messages_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < messages_.size(); i++) {
        output.writeMessage(1, messages_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < messages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, messages_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessageOuterClass.MessageList)) {
        return super.equals(obj);
      }
      MessageOuterClass.MessageList other = (MessageOuterClass.MessageList) obj;

      if (!getMessagesList()
          .equals(other.getMessagesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMessagesCount() > 0) {
        hash = (37 * hash) + MESSAGES_FIELD_NUMBER;
        hash = (53 * hash) + getMessagesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessageOuterClass.MessageList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageOuterClass.MessageList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageOuterClass.MessageList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageOuterClass.MessageList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageOuterClass.MessageList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageOuterClass.MessageList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageOuterClass.MessageList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageOuterClass.MessageList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static MessageOuterClass.MessageList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static MessageOuterClass.MessageList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageOuterClass.MessageList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageOuterClass.MessageList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessageOuterClass.MessageList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MessageList)
        MessageOuterClass.MessageListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageOuterClass.internal_static_MessageList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageOuterClass.internal_static_MessageList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageOuterClass.MessageList.class, MessageOuterClass.MessageList.Builder.class);
      }

      // Construct using MessageOuterClass.MessageList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
        } else {
          messages_ = null;
          messagesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageOuterClass.internal_static_MessageList_descriptor;
      }

      @java.lang.Override
      public MessageOuterClass.MessageList getDefaultInstanceForType() {
        return MessageOuterClass.MessageList.getDefaultInstance();
      }

      @java.lang.Override
      public MessageOuterClass.MessageList build() {
        MessageOuterClass.MessageList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MessageOuterClass.MessageList buildPartial() {
        MessageOuterClass.MessageList result = new MessageOuterClass.MessageList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(MessageOuterClass.MessageList result) {
        if (messagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            messages_ = java.util.Collections.unmodifiableList(messages_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.messages_ = messages_;
        } else {
          result.messages_ = messagesBuilder_.build();
        }
      }

      private void buildPartial0(MessageOuterClass.MessageList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageOuterClass.MessageList) {
          return mergeFrom((MessageOuterClass.MessageList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageOuterClass.MessageList other) {
        if (other == MessageOuterClass.MessageList.getDefaultInstance()) return this;
        if (messagesBuilder_ == null) {
          if (!other.messages_.isEmpty()) {
            if (messages_.isEmpty()) {
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMessagesIsMutable();
              messages_.addAll(other.messages_);
            }
            onChanged();
          }
        } else {
          if (!other.messages_.isEmpty()) {
            if (messagesBuilder_.isEmpty()) {
              messagesBuilder_.dispose();
              messagesBuilder_ = null;
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
              messagesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMessagesFieldBuilder() : null;
            } else {
              messagesBuilder_.addAllMessages(other.messages_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                MessageOuterClass.Message m =
                    input.readMessage(
                        MessageOuterClass.Message.parser(),
                        extensionRegistry);
                if (messagesBuilder_ == null) {
                  ensureMessagesIsMutable();
                  messages_.add(m);
                } else {
                  messagesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<MessageOuterClass.Message> messages_ =
        java.util.Collections.emptyList();
      private void ensureMessagesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          messages_ = new java.util.ArrayList<MessageOuterClass.Message>(messages_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          MessageOuterClass.Message, MessageOuterClass.Message.Builder, MessageOuterClass.MessageOrBuilder> messagesBuilder_;

      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public java.util.List<MessageOuterClass.Message> getMessagesList() {
        if (messagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(messages_);
        } else {
          return messagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public int getMessagesCount() {
        if (messagesBuilder_ == null) {
          return messages_.size();
        } else {
          return messagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public MessageOuterClass.Message getMessages(int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);
        } else {
          return messagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public Builder setMessages(
          int index, MessageOuterClass.Message value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.set(index, value);
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public Builder setMessages(
          int index, MessageOuterClass.Message.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.set(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public Builder addMessages(MessageOuterClass.Message value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public Builder addMessages(
          int index, MessageOuterClass.Message value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(index, value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public Builder addMessages(
          MessageOuterClass.Message.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public Builder addMessages(
          int index, MessageOuterClass.Message.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public Builder addAllMessages(
          java.lang.Iterable<? extends MessageOuterClass.Message> values) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, messages_);
          onChanged();
        } else {
          messagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public Builder clearMessages() {
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public Builder removeMessages(int index) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.remove(index);
          onChanged();
        } else {
          messagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public MessageOuterClass.Message.Builder getMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public MessageOuterClass.MessageOrBuilder getMessagesOrBuilder(
          int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);  } else {
          return messagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public java.util.List<? extends MessageOuterClass.MessageOrBuilder> 
           getMessagesOrBuilderList() {
        if (messagesBuilder_ != null) {
          return messagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(messages_);
        }
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public MessageOuterClass.Message.Builder addMessagesBuilder() {
        return getMessagesFieldBuilder().addBuilder(
            MessageOuterClass.Message.getDefaultInstance());
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public MessageOuterClass.Message.Builder addMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().addBuilder(
            index, MessageOuterClass.Message.getDefaultInstance());
      }
      /**
       * <code>repeated .Message messages = 1;</code>
       */
      public java.util.List<MessageOuterClass.Message.Builder> 
           getMessagesBuilderList() {
        return getMessagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          MessageOuterClass.Message, MessageOuterClass.Message.Builder, MessageOuterClass.MessageOrBuilder> 
          getMessagesFieldBuilder() {
        if (messagesBuilder_ == null) {
          messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              MessageOuterClass.Message, MessageOuterClass.Message.Builder, MessageOuterClass.MessageOrBuilder>(
                  messages_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          messages_ = null;
        }
        return messagesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MessageList)
    }

    // @@protoc_insertion_point(class_scope:MessageList)
    private static final MessageOuterClass.MessageList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessageOuterClass.MessageList();
    }

    public static MessageOuterClass.MessageList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageList>
        PARSER = new com.google.protobuf.AbstractParser<MessageList>() {
      @java.lang.Override
      public MessageList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MessageList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MessageOuterClass.MessageList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\032\037google/protobuf/timesta" +
      "mp.proto\"\210\001\n\007Message\022\026\n\016chatIdentifier\030\001" +
      " \001(\t\022\023\n\013membersLast\030\002 \001(\t\022\024\n\014belongNumbe" +
      "r\030\003 \001(\t\022,\n\010sendDate\030\004 \001(\0132\032.google.proto" +
      "buf.Timestamp\022\014\n\004text\030\005 \001(\t\")\n\013MessageLi" +
      "st\022\032\n\010messages\030\001 \003(\0132\010.Messageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "ChatIdentifier", "MembersLast", "BelongNumber", "SendDate", "Text", });
    internal_static_MessageList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MessageList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageList_descriptor,
        new java.lang.String[] { "Messages", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
