server:
  port: 9191
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: otus.p12
    key-store-password: 123456
    key-alias: otus
  truststore:
    store: truststore.p12
    password: 123456

logging:
  level:
    root: debug

spring:
  sql:
    init:
      platform: hsqldb
  jpa:
    defer-datasource-initialization: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/realm_test
      client:
        registration:
          keycloak:
            client-id: books
            client-secret: b8ppT9ZWWltpHq9cCnW2cAroCLC93lmn
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/realm_test
            user-name-attribute: preferred_username

