server:
  port: 8181
  servlet:
    context-path: /app
spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/hwHttps
    username: usr
    password: pwd
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: otusapi.p12
#    key-store-password: 123456
#    key-alias: otusapi

logging:
  level:
    root: debug

