server:
  port: 8189
  servlet:
    context-path: /password_changer
spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/configDB
    username: usr
    password: pwd
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE