server:
  port: 8189
  servlet:
    context-path: /app
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: otus1.p12
    key-store-password: 123456
    key-alias: otus
  truststore:
    store: truststore.p12
    password: 123456
spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/hwHttps
    username: usr
    password: pwd
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE