spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.1:5432/item?useUnicode=true&characterEncoding=UTF8
    username: postgres
    password: 11223344