server:
  port: 8189
  servlet:
    context-path: /password_changer
spring:
  datasource:
      platform: postgres
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/configDB
      username: ${CONFIGURATION_DB_USERNAME}
      password: ${CONFIGURATION_DB_PASSWORD}
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${CONFIGURATION_EMAIL_USERNAME}
    password: ${CONFIGURATION_EMAIL_PASSWORD}
    subject: Подтверждение готовности проведения работ
    template: emailTemplate
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
telegram:
  bot:
    botUsername: ${CONFIGURATION_BOT_USERNAME}
    token: ${CONFIGURATION_BOT_TOKEN}
    chatId: ${CONFIGURATION_BOT_CHAT_ID}
    botMessageText: Работы по обновлению пароля УЗ в БД завершены