server:
  port: 8181
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: otusapi2.p12
    key-store-password: 123456
    key-alias: otusapi

logging:
  level:
    root: debug

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/realm_test

